[server]
enableStaticServing = true
maxUploadSize=50

[theme]
primaryColor = "#4B4BC8"

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = true

[client]
toolbarMode = "minimal"

[custom_css]
css = """
    .block-container {
        padding-top: 1rem;
    }
    .block-container > div:first-child {
        margin-top: -4rem;
    }
    header {
        visibility: hidden;
    }
    #MainMenu {
        visibility: hidden;
    }
    footer {
        visibility: hidden;
    }
"""
